serverIP: 0.0.0.0
serverPort: 8282
bufferWidth: 1100
bufferHeight: 1100
canvasWidth: 1024
canvasHeight: 1024
canvasFile: "/tmp/canvas.png"
showLabels: false
showLegend: true
showLegendServerInfo: true
showLegendStats: true
showLegendClientStats: true
legendX: 2
legendY: 10