serverIP: 0.0.0.0
serverPort: 8282
bufferWidth: 1300
bufferHeight: 1100
canvasWidth: 1000
canvasHeight: 1000
canvasFile: "/tmp/canvas.png"
showLabels: false
showLegend: true
showLegendServerInfo: true
showLegendStats: true
showLegendClientStats: true
legendX: 2
legendY: 10
legendFontSize: 12
legendFontColor: "ffff00"
configReloadIntervallSeconds: 10